### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by FunkyLoveCow** [finish06/pyunifi#36]
I have very simple code, taken from the gather stats example:

```
from pyunifi.controller import Controller

c = Controller('192.168.100.1', 'admin', 'password', ssl_verify=False)  # Obviously these aren't real, but assume they are
stats = c.get_statistics_last_24h()
```

This throws an error:

```
Traceback (most recent call last):
  File "first_connect.py", line 4, in <module>
    stats = c.get_statistics_last_24h()
  File "/home/dacow/.virtualenvs/unifi/lib/python3.6/site-packages/pyunifi/controller.py", line 168, in get_statistics_last_24h
    return self.get_statistics_24h(time())
TypeError: 'module' object is not callable
```

As far as I can tell, this is exactly what is happening in [unifi-save-statistics](https://github.com/finish06/pyunifi/blob/master/unifi-save-statistics).

Why am I failing when getting statistics?

For what it's worth, I can run `c.get_aps()` and `c.get_clients()` without an issue.

**Comment by jamenlang** [comment]
I'm also getting this on line 168. 
I'd love to be able to get statistics again.
